### ISSUE TITLE
Homepage defects

### ISSUE THREAD

**Issue by luca-aki** [testrightexam/testrightexam.github.io#12]
@prati-bha @ankitc26 Fix the following in homepage:

In Slide 2, there is a while line between navbar and the page. 
In Slide 3, in the footer you've written different things in the desktop view and mobile view. 
In Slide 3, the follow us section leave out some space, maybe rearrange them and use fafa icons if possible.

**Comment by prati-bha** [comment]
i have 

> @prati-bha @ankitc26 Fix the following in homepage:
> 
> In Slide 2, there is a while line between navbar and the page.
> In Slide 3, in the footer you've written different things in the desktop view and mobile view.
> In Slide 3, the follow us section leave out some space, maybe rearrange them and use fafa icons if possible.

i fixed the issues, the white line u are able to see is something u will not get in real mobile... i am not able to get what is that but that do not comes in orignal mobile.

other footer issues solvd check for both web and mobile view
